# Hashnode Blog Readmde
name: HashnodeBlogReadme
on:
  schedule:
    # Runs every day at 9am UTC
    - cron: '25 * * * *'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Get RSS Feed
        uses: kohrongying/readme-the-rss@master
        with:
          # Change the feedURL to yourHashnodeBlog.com/rss.xml
          feed_url: https://ooshimus.com/rss.xml
          count: 10
      - name: Commit file changes
        run: |
            git config --global user.name 'Aiyush-G'
            git config --global user.email 'agupta17@agsb.co.uk'
            git add .
            git diff --quiet --cached || git commit -m "Update README"  
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
